name: Test
on: [push]
jobs:
  load_on_all_supported_runner_systems:
    name: Loads on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            macos-10.15,
            macos-latest,
            ubuntu-16.04,
            ubuntu-18.04,
            ubuntu-latest,
            windows-2019,
            windows-latest,
          ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
  load_specific_version:
    name: Loads v${matrix.version}
    strategy:
      matrix:
        version: ["latest", "0.10.0"]
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: ${matrix.version}
